apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-eomployee-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-eomployee
  template:
    metadata:
      labels:
        app: mongo-eomployee
    spec:
      volumes:
        - name: employee-storage
          persistentVolumeClaim:
            claimName: employee-database-pvc
      containers:
        - name: mongo-eomployee
          image: mongo
          volumeMounts:
            - name: employee-storage
              mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-eomployee-service
spec:
  selector:
    app: mongo-eomployee
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
